-- Seed 10 sample cars with rental categories
INSERT INTO cars (slug, brand, model, year, category, transmission, fuel_type, seats, doors, daily_rate, security_deposit, description, features, color, is_featured, is_available, rental_categories)
VALUES
  ('bmw-5-series-2023', 'BMW', '5 Series', 2023, 'luxury', 'automatic', 'diesel', 5, 4, 150, 500, 'Executive luxury sedan with premium interior and advanced driver assistance systems.', ARRAY['Bluetooth', 'Backup Camera', 'Cruise Control', 'Leather Seats', 'GPS Navigation', 'Parking Sensors'], 'Navy Blue', true, true, ARRAY['business-travel', 'airport-pickup']),
  ('mercedes-v-class-2024', 'Mercedes-Benz', 'V-Class', 2024, 'van', 'automatic', 'diesel', 7, 5, 200, 800, 'Spacious luxury van perfect for family trips and group transfers. Ample luggage space.', ARRAY['Bluetooth', 'Backup Camera', 'Cruise Control', 'Leather Seats', 'Rear AC', 'USB Charging'], 'Silver', true, true, ARRAY['family-trips', 'airport-pickup']),
  ('porsche-911-2023', 'Porsche', '911', 2023, 'sports', 'automatic', 'gasoline', 4, 2, 350, 1500, 'Iconic sports car for an unforgettable weekend escape. Raw power meets precision engineering.', ARRAY['Bluetooth', 'Sport Seats', 'Bose Sound System', 'Launch Control', 'Sport Exhaust'], 'Carrara White', true, true, ARRAY['wedding', 'weekend-escape']),
  ('toyota-highlander-2023', 'Toyota', 'Highlander', 2023, 'suv', 'automatic', 'hybrid', 7, 5, 120, 400, 'Reliable family SUV with hybrid efficiency. Perfect for long road trips and daily driving.', ARRAY['Bluetooth', 'Backup Camera', 'Cruise Control', 'Third Row', 'Apple CarPlay', 'Lane Assist'], 'Pearl White', true, true, ARRAY['family-trips', 'weekend-escape']),
  ('audi-a6-2024', 'Audi', 'A6', 2024, 'luxury', 'automatic', 'diesel', 5, 4, 160, 600, 'Sophisticated business sedan with Quattro all-wheel drive and virtual cockpit.', ARRAY['Bluetooth', 'Backup Camera', 'Cruise Control', 'Leather Seats', 'Virtual Cockpit', 'Ambient Lighting'], 'Phantom Black', true, true, ARRAY['business-travel', 'airport-pickup', 'wedding']),
  ('volkswagen-multivan-2023', 'Volkswagen', 'Multivan', 2023, 'van', 'automatic', 'diesel', 7, 5, 180, 700, 'Versatile people carrier with flexible seating configurations. Ideal for airport transfers.', ARRAY['Bluetooth', 'Backup Camera', 'Cruise Control', 'Sliding Doors', 'Foldable Seats', 'Roof Rails'], 'Deep Blue', false, true, ARRAY['family-trips', 'airport-pickup']),
  ('ford-mustang-2024', 'Ford', 'Mustang', 2024, 'sports', 'manual', 'gasoline', 4, 2, 190, 800, 'American muscle icon. Feel the thrill of the open road with this powerful coupe.', ARRAY['Bluetooth', 'Backup Camera', 'Cruise Control', 'Sport Mode', 'Digital Dash', 'Premium Audio'], 'Race Red', true, true, ARRAY['weekend-escape']),
  ('honda-cr-v-2023', 'Honda', 'CR-V', 2023, 'suv', 'automatic', 'gasoline', 5, 5, 95, 300, 'Compact SUV with excellent fuel economy and Honda reliability. Great for city driving.', ARRAY['Bluetooth', 'Backup Camera', 'Cruise Control', 'Apple CarPlay', 'LaneWatch', 'LED Headlights'], 'Sonic Gray', false, true, ARRAY['family-trips']),
  ('nissan-altima-2023', 'Nissan', 'Altima', 2023, 'sedan', 'automatic', 'gasoline', 5, 4, 75, 250, 'Affordable and comfortable sedan with great fuel economy. Perfect for daily rentals.', ARRAY['Bluetooth', 'Backup Camera', 'Cruise Control', 'Apple CarPlay', 'Keyless Entry'], 'Gun Metallic', false, true, ARRAY[]::TEXT[]),
  ('range-rover-velar-2024', 'Range Rover', 'Velar', 2024, 'luxury', 'automatic', 'diesel', 5, 5, 250, 1000, 'Luxury SUV with stunning design and off-road capability. The ultimate wedding or business statement.', ARRAY['Bluetooth', 'Backup Camera', 'Cruise Control', 'Leather Seats', 'Panoramic Roof', 'Air Suspension', 'Terrain Response'], 'Santorini Black', true, true, ARRAY['wedding', 'business-travel', 'weekend-escape']);
